/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActForm: typeof import('./components/ActForm.vue')['default']
    AdditionalData: typeof import('./components/AdditionalData.vue')['default']
    Address: typeof import('./components/Address.vue')['default']
    Apartment: typeof import('./components/Apartment.vue')['default']
    ApartmentInternalSystems: typeof import('./components/ApartmentInternalSystems.vue')['default']
    AppBar: typeof import('./components/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BuildingClass: typeof import('./components/BuildingClass.vue')['default']
    BuildingPropertiesFirst: typeof import('./components/BuildingPropertiesFirst.vue')['default']
    BuildingPropertiesSecond: typeof import('./components/BuildingPropertiesSecond.vue')['default']
    BuildingPropertiesThird: typeof import('./components/BuildingPropertiesThird.vue')['default']
    CadastreNumber: typeof import('./components/CadastreNumber.vue')['default']
    ConclusionType: typeof import('./components/ConclusionType.vue')['default']
    ConstructionElements: typeof import('./components/ConstructionElements.vue')['default']
    CulturalHeritage: typeof import('./components/CulturalHeritage.vue')['default']
    CustomAddress: typeof import('./components/CustomAddress.vue')['default']
    CustomPassport: typeof import('./components/CustomPassport.vue')['default']
    CustomTaxId: typeof import('./components/CustomTaxId.vue')['default']
    DictionaryValue: typeof import('./components/DictionaryValue.vue')['default']
    Document: typeof import('./components/Document.vue')['default']
    DocumentReference: typeof import('./components/DocumentReference.vue')['default']
    FirstBuildingProperties: typeof import('./components/FirstBuildingProperties.vue')['default']
    FunctionalPurpose: typeof import('./components/FunctionalPurpose.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InternalSystems: typeof import('./components/InternalSystems.vue')['default']
    InterntalSystems: typeof import('./components/InterntalSystems.vue')['default']
    LandCategory: typeof import('./components/LandCategory.vue')['default']
    NumericField: typeof import('./components/NumericField.vue')['default']
    OrganizationCode: typeof import('./components/OrganizationCode.vue')['default']
    OrganizationForm: typeof import('./components/OrganizationForm.vue')['default']
    PersonForm: typeof import('./components/PersonForm.vue')['default']
    PersonPassport: typeof import('./components/PersonPassport.vue')['default']
    PersonTaxId: typeof import('./components/PersonTaxId.vue')['default']
    RenderDocument: typeof import('./components/RenderDocument.vue')['default']
    RentInfo: typeof import('./components/RentInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabularData: typeof import('./components/TabularData.vue')['default']
    Territory: typeof import('./components/Territory.vue')['default']
    TextData: typeof import('./components/TextData.vue')['default']
    WorkPanel: typeof import('./components/WorkPanel.vue')['default']
  }
}
