/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActFilters: typeof import('./components/Extra/ActFilters.vue')['default']
    ActForm: typeof import('./components/Forms/ActForm.vue')['default']
    ActList: typeof import('./components/Extra/ActList.vue')['default']
    AdditionalData: typeof import('./components/BasicFields/AdditionalData.vue')['default']
    AdminPanel: typeof import('./components/AdminPanel.vue')['default']
    Apartment: typeof import('./components/ComplexFields/Apartment.vue')['default']
    ApartmentInternalSystems: typeof import('./components/ComplexFields/ApartmentInternalSystems.vue')['default']
    AppBar: typeof import('./components/AppBar.vue')['default']
    BuildingClass: typeof import('./components/BasicFields/BuildingClass.vue')['default']
    BuildingPropertiesFirst: typeof import('./components/ComplexFields/BuildingPropertiesFirst.vue')['default']
    BuildingPropertiesSecond: typeof import('./components/ComplexFields/BuildingPropertiesSecond.vue')['default']
    BuildingPropertiesThird: typeof import('./components/ComplexFields/BuildingPropertiesThird.vue')['default']
    CadastreNumber: typeof import('./components/BasicFields/CadastreNumber.vue')['default']
    CommissionForm: typeof import('./components/Forms/CommissionForm.vue')['default']
    CommissionMemberDialog: typeof import('./components/Forms/CommissionMemberDialog.vue')['default']
    CommissionMembersList: typeof import('./components/Extra/CommissionMembersList.vue')['default']
    ConclusionType: typeof import('./components/BasicFields/ConclusionType.vue')['default']
    ConstructionElements: typeof import('./components/ComplexFields/ConstructionElements.vue')['default']
    CulturalHeritage: typeof import('./components/Forms/CulturalHeritage.vue')['default']
    CustomAddress: typeof import('./components/ComplexFields/CustomAddress.vue')['default']
    CustomDate: typeof import('./components/BasicFields/CustomDate.vue')['default']
    DictionaryValue: typeof import('./components/BasicFields/DictionaryValue.vue')['default']
    DocumentReference: typeof import('./components/Forms/DocumentReference.vue')['default']
    FunctionalPurpose: typeof import('./components/ComplexFields/FunctionalPurpose.vue')['default']
    InternalSystems: typeof import('./components/ComplexFields/InternalSystems.vue')['default']
    InvolvedList: typeof import('./components/Extra/InvolvedList.vue')['default']
    LandCategory: typeof import('./components/BasicFields/LandCategory.vue')['default']
    NumericField: typeof import('./components/BasicFields/NumericField.vue')['default']
    OrganizationCode: typeof import('./components/BasicFields/OrganizationCode.vue')['default']
    OrganizationForm: typeof import('./components/Forms/OrganizationForm.vue')['default']
    PersonDialog: typeof import('./components/Forms/PersonDialog.vue')['default']
    PersonForm: typeof import('./components/Forms/PersonForm.vue')['default']
    PersonPassport: typeof import('./components/BasicFields/PersonPassport.vue')['default']
    PersonTaxId: typeof import('./components/BasicFields/PersonTaxId.vue')['default']
    RenderDocument: typeof import('./components/RenderDocument.vue')['default']
    RentInfo: typeof import('./components/ComplexFields/RentInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPanel: typeof import('./components/SearchPanel.vue')['default']
    SignForm: typeof import('./components/Forms/SignForm.vue')['default']
    TabularData: typeof import('./components/ComplexFields/TabularData.vue')['default']
    Territory: typeof import('./components/BasicFields/Territory.vue')['default']
    TextData: typeof import('./components/ComplexFields/TextData.vue')['default']
    UploadBox: typeof import('./components/BasicFields/CustomFile/UploadBox.vue')['default']
    WorkPanel: typeof import('./components/WorkPanel.vue')['default']
  }
}
